-- Adicionando os campos preenchidos do banco legado (SET) que faltavam.

-- PRODUTOS
ALTER TABLE produto
  ADD COLUMN preco_custo NUMERIC(16,4),
  ADD COLUMN preco_compra NUMERIC(16,4),
  ADD COLUMN p_lucro NUMERIC(16,4),
  ADD COLUMN p_lucro2 NUMERIC(16,4),
  ADD COLUMN p_lucro3 NUMERIC(16,4),
  ADD COLUMN v_lucro NUMERIC(16,4),
  ADD COLUMN v_lucro2 NUMERIC(16,4),
  ADD COLUMN v_lucro3 NUMERIC(16,4),
  ADD COLUMN preco_venda2 NUMERIC(16,4),
  ADD COLUMN preco_venda3 NUMERIC(16,4),
  ADD COLUMN preco_especial NUMERIC(16,4),
  ADD COLUMN qtde_min NUMERIC(16,4),
  ADD COLUMN qtde_max NUMERIC(16,4),
  ADD COLUMN qtde_reservado NUMERIC(16,4),
  ADD COLUMN qtde_producao NUMERIC(16,4),
  ADD COLUMN grupo TEXT,
  ADD COLUMN subgrupo TEXT,
  ADD COLUMN ref_origi TEXT,
  ADD COLUMN cod_fabricante TEXT,
  ADD COLUMN controla_estoque TEXT,
  ADD COLUMN situacao TEXT,
  ADD COLUMN prod_prop TEXT,
  ADD COLUMN classe TEXT,
  ADD COLUMN prod_especifico TEXT,
  ADD COLUMN cst_icms TEXT,
  ADD COLUMN cbenef TEXT,
  ADD COLUMN data_cad TIMESTAMPTZ,
  ADD COLUMN data_alt TIMESTAMPTZ,
  ADD COLUMN data_alt_ncm TIMESTAMPTZ,
  ADD COLUMN usuario_cad TEXT,
  ADD COLUMN usuario_alt TEXT,
  ADD COLUMN anota TEXT,
  ADD COLUMN un_compra TEXT;

-- CLIENTES
ALTER TABLE cliente
  ADD COLUMN tipo TEXT,
  ADD COLUMN razao TEXT,
  ADD COLUMN fantasia TEXT,
  ADD COLUMN rg TEXT,
  ADD COLUMN ie TEXT,
  ADD COLUMN data_nasc DATE,
  ADD COLUMN idade TEXT,
  ADD COLUMN sexo TEXT,
  ADD COLUMN pfis_nome_pai TEXT,
  ADD COLUMN pfis_nome_mae TEXT,
  ADD COLUMN pfis_nome_conj TEXT,
  ADD COLUMN pfis_empresa_conj TEXT,
  ADD COLUMN pfis_renda_conj NUMERIC(16,4),
  ADD COLUMN pfis_fone_conj TEXT,
  ADD COLUMN pfis_local_trab TEXT,
  ADD COLUMN pfis_profissao TEXT,
  ADD COLUMN ref_comerciais TEXT,
  ADD COLUMN limite_cred NUMERIC(16,4),
  ADD COLUMN bloqueado TEXT,
  ADD COLUMN dia_vencimento INTEGER,
  ADD COLUMN fone2 TEXT,
  ADD COLUMN fone3 TEXT,
  ADD COLUMN fone1_tipo TEXT,
  ADD COLUMN whats_fone1 TEXT,
  ADD COLUMN complemento TEXT,
  ADD COLUMN ent_complemento TEXT,
  ADD COLUMN anotacoes TEXT,
  ADD COLUMN campo1 TEXT,
  ADD COLUMN campo2 TEXT,
  ADD COLUMN tab_preco1 TEXT,
  ADD COLUMN tab_preco2 TEXT,
  ADD COLUMN tab_preco3 TEXT,
  ADD COLUMN data_cad TIMESTAMPTZ,
  ADD COLUMN data_alt TIMESTAMPTZ,
  ADD COLUMN usuario_cad TEXT,
  ADD COLUMN usuario_alt TEXT;
